// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skpzdlpfgbbpuxdrptkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrcHpkbHBmZ2JicHV4ZHJwdGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0OTY0ODgsImV4cCI6MjA2NzA3MjQ4OH0.2GV8t6895GknnIBhhjh-nNDvpNBNL_Shp6KIkBa4lb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});